import { useState, type ReactNode } from "react";
import { orderService } from "../orderService";
import { useNavigate } from "react-router";
import type { RequestActivity, RequestMessage, ReviewRequest, ReviewRequestStatus } from "../types";
import { getAllowedTransitions, isChatAvailable, WORKFLOW, type WorkflowActor } from "../../../domain/workflow";

export const money = (amount: number | null, currency: string) => amount == null ? "—" : currency === "IDR" ? `Rp${amount.toLocaleString("id-ID")}` : new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount);
export const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

const statusAction: Record<ReviewRequestStatus,string>={DRAFT_PREVIEW:"Send for Review",SUBMITTED:"View Submission",UNDER_REVIEW:"Send Message",WAITING_FOR_REPLY:"Reply to Artisan",READY_FOR_APPROVAL:"Review & Approve",REVISION_REQUESTED:"View Revision",READY_FOR_CHECKOUT:"Proceed to Checkout",PAYMENT_PENDING:"View Pending Order",PAID:"View Order",IN_PRODUCTION:"View Production",SHIPPED:"Track Shipment",COMPLETED:"View Creation",CANCELLED:"Return to Drafts"};

const overviewDetails: Record<ReviewRequestStatus, string> = {
  DRAFT_PREVIEW: "Check your creation title, story, preferred notes, and notes to avoid. Nothing has been sent to our artisans yet.",
  SUBMITTED: "Your story and preferences are safely recorded. An Indische artisan will begin by interpreting the atmosphere, memories, and notes you shared.",
  UNDER_REVIEW: "Our artisan is studying your story, preferred notes, and notes to avoid. The review will prepare an olfactive interpretation, recommendations, production estimate, and final price.",
  WAITING_FOR_REPLY: "Your review is paused while the artisan waits for your answer. Reply through Chat so the interpretation can continue.",
  READY_FOR_APPROVAL: "The artisan interpretation and proposed details are complete. Review the recommendations and approve them when they feel right.",
  REVISION_REQUESTED: "Your requested changes are preserved until an artisan resumes review.",
  READY_FOR_CHECKOUT: "Your approved creation details and final price are locked. You may continue to the development checkout when ready.",
  PAYMENT_PENDING: "Your creation is approved, but production has not started. Complete checkout to confirm the commission.",
  PAID: "Payment is confirmed, but production starts only after an administrator begins it.",
  IN_PRODUCTION: "Formula development and preparation are underway. Important progress will be recorded in Activity.",
  SHIPPED: "Your completed creation has left The Hall. Shipment information and tracking are available below.",
  COMPLETED: "Your bespoke fragrance journey is complete. You can revisit the finished creation or begin a new story.",
  CANCELLED: "This request is closed and will not continue to artisan review or production."
};

export function CreationIdentity({ request, includeDemo=false }: { request: ReviewRequest; includeDemo?:boolean }) { const navigate=useNavigate(); const[open,setOpen]=useState(false); const[items,setItems]=useState(()=>orderService.getRequests(includeDemo)); const refresh=()=>setItems(orderService.getRequests(includeDemo)); return <section className="od-identity"><div className="od-order-picker"><button type="button" aria-expanded={open} onClick={()=>{refresh();setOpen(value=>!value)}}>MY ORDERS <span>{open?"▴":"▾"}</span></button><span>›</span><b>{request.perfumeName.toUpperCase()}</b>{open&&<div className="od-order-menu">{items.length?items.map(item=><button type="button" className={item.id===request.id?"active":""} key={item.id} onClick={()=>{setOpen(false);navigate(`/my-orders/${item.id}${includeDemo?"?dev=1":""}`)}}><span><strong>{item.perfumeName}</strong><small>{item.requestNumber}</small></span><em>{WORKFLOW[item.status].label}</em></button>):<p>No submitted creations yet.</p>}</div>}</div><div><h1>{request.perfumeName}</h1><span className="od-status-pill">{WORKFLOW[request.status].label}</span></div><p>{request.concentration} <b>•</b> {request.bottleSize} <b>•</b> Created by account holder</p><div className="od-identifiers"><span><small>Request No.</small>{request.requestNumber}</span><span><small>Submitted On</small>{formatDate(request.submittedAt)}</span><span><small>Last Update</small>{formatDate(request.lastUpdatedAt)}</span></div></section> }

const journey = [{ key:"UNDER_REVIEW", label:"Submitted", icon:"✓" },{ key:"READY_FOR_APPROVAL", label:"Under Review", icon:"⌕" },{ key:"READY_FOR_CHECKOUT", label:"Approval", icon:"♢" },{ key:"PAYMENT_PENDING", label:"Checkout", icon:"△" },{ key:"IN_PRODUCTION", label:"Production", icon:"✧" },{ key:"SHIPPED", label:"Delivery", icon:"◇" }];
const rank: Record<ReviewRequestStatus, number> = { DRAFT_PREVIEW:0, SUBMITTED:1, UNDER_REVIEW:2, WAITING_FOR_REPLY:2, READY_FOR_APPROVAL:3, REVISION_REQUESTED:3, READY_FOR_CHECKOUT:4, PAYMENT_PENDING:5, PAID:5, IN_PRODUCTION:6, SHIPPED:7, COMPLETED:8, CANCELLED:0 };
export function JourneyTimeline({ request }: { request: ReviewRequest }) { const progress = rank[request.status]; const activeSteps=progress===0?0:Math.max(1,Math.ceil(progress*.75)); return <section className="od-journey">{journey.map((step,index)=><div className={index < activeSteps ? "done" : ""} key={step.key}><i>{step.icon}</i><strong>{step.label}</strong><small>{index===0?(request.submittedAt?formatDate(request.submittedAt):"Not submitted"):index===1?"Artisan review":index===2?"Review details":index===3?"Confirm payment":index===4?"Being crafted":"Delivered to you"}</small></div>)}</section> }

function NoteList({ title, notes }: { title:string; notes:string[] }) { return <div><small>{title}</small>{notes.map((note,index)=><p key={note}><b>{["✦","❀","❧","✣"][index%4]}</b>{note}</p>)}</div> }
export function CreationSummary({ request }: { request: ReviewRequest }) { const described=request.creationMode==="described"||request.concentration==="To be interpreted"; return <section className="od-panel od-creation"><h2>❧ &nbsp; YOUR CREATION</h2><div className="od-creation-main"><div className="od-bottle"><span>{request.perfumeName}</span></div><div><small>Fragrance Direction</small><div className="od-chips">{request.fragranceDirection.map(x=><span key={x}>{x}</span>)}</div><div className="od-notes-grid"><NoteList title="TOP NOTES" notes={request.topNotes}/><NoteList title="HEART NOTES" notes={request.heartNotes}/><NoteList title="BASE NOTES" notes={request.baseNotes}/></div></div></div><div className={`od-brief-story${described?" od-brief-story--single":""}`}><div><h3>FRAGRANCE BRIEF</h3><p>{request.fragranceBrief}</p><button>View Full Brief &nbsp; ◉</button></div>{!described&&<div><h3>STORY CARD PREVIEW</h3><div className="od-story" style={{backgroundImage:`url(${request.storyCardData.imageUrl})`}}><strong>{request.storyCardData.title}</strong><small>{request.storyCardData.subtitle}</small></div><button>⇩ &nbsp; View Story Card</button></div>}</div></section> }
export function NotesYouSent({ request }: { request: ReviewRequest }) { return <section className="od-panel od-customer-notes"><h2>❧ &nbsp; NOTES YOU SENT</h2><p>“{request.customerNotes}”</p><button>✎ &nbsp; Edit Notes</button></section> }

export function OverviewPanel({ request }: { request: ReviewRequest }) { const copy=WORKFLOW[request.status]; return <div><section className="od-overview-callout"><h3>✥ &nbsp; {copy.label.toUpperCase()}</h3><p>{copy.description}</p><small>We will update you as soon as we have news.</small></section>{request.status==="READY_FOR_APPROVAL"&&<ArtisanReviewPanel request={request}/>}<h3 className="od-section-title">⚜ &nbsp; LETTERS WITH INDISCHE ARTISAN</h3></div> }
export function ArtisanReviewPanel({ request }: { request: ReviewRequest }) { if(!request.artisanReview)return null; return <section className="od-artisan-review"><h3>ARTISAN REVIEW</h3><p>{request.artisanReview.summary}</p><dl><dt>Olfactive direction</dt><dd>{request.artisanReview.olfactiveDirection}</dd><dt>Recommended adjustments</dt><dd>{request.recommendedAdjustments.join(" · ")}</dd><dt>Included</dt><dd>{request.includedItems.join(" · ")}</dd><dt>Production</dt><dd>{request.estimatedProduction} · {request.revisionsIncluded} revision included</dd></dl></section> }

export function ChatPanel({ requestId,status,messages }: { requestId:string;status:ReviewRequestStatus;messages:RequestMessage[] }) { const [text,setText]=useState(""); const enabled=isChatAvailable(status); const send=async()=>{if(!enabled||!text.trim())return;await orderService.sendMessage(requestId,text);setText("")}; return <section className="od-chat">{messages.length?messages.map(message=><article className={message.senderRole} key={message.id}><div className="od-avatar">{message.senderRole==="artisan"?"IA":message.senderRole==="system"?"✦":"YO"}</div><div><header><strong>{message.senderName}</strong><small>{formatDate(message.createdAt)}</small></header><p>{message.message}</p></div></article>):<p className="od-empty">No letters yet. Your conversation with the artisan will appear here.</p>}<div className="od-compose"><input disabled={!enabled} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} placeholder={enabled?"Type your message...":"Chat is unavailable for this status."}/><button disabled={!enabled} onClick={()=>void send()}>➤</button></div><small>You will be notified here and via email for any updates.</small></section> }
export function ActivityPanel({ activity }: { activity:RequestActivity[] }) { return <section className="od-activity">{activity.length?activity.slice().reverse().map(item=><article key={item.id}><i>✓</i><div><strong>{item.label}</strong><small>{formatDate(item.createdAt)}</small></div></article>):<p className="od-empty">No activity has been recorded yet.</p>}</section> }
export function RequestTabs({ request, messages, activity }: { request:ReviewRequest;messages:RequestMessage[];activity:RequestActivity[] }) { const [tab,setTab]=useState<"chat"|"activity">("chat"); return <section className="od-panel od-center"><nav><button className={tab==="chat"?"active":""} onClick={()=>setTab("chat")}>CHAT <span>{messages.filter(x=>!x.readAt&&x.senderRole==="artisan").length}</span></button><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>ACTIVITY</button></nav>{tab==="chat"&&<ChatPanel requestId={request.id} status={request.status} messages={messages}/>} {tab==="activity"&&<ActivityPanel activity={activity}/>}</section> }

function SideCard({ title,children,className="" }: {title:string;children:ReactNode;className?:string}) { return <section className={`od-panel od-side-card ${className}`}><h2>❧ &nbsp; {title}</h2>{children}</section> }
export function CurrentStatusCard({ request }: { request:ReviewRequest }) { const copy=WORKFLOW[request.status]; return <SideCard title="CURRENT STATUS"><h3 className="od-current"><i/> {copy.label}</h3><p>{copy.description}</p><p className="od-status-overview">{overviewDetails[request.status]}</p>{request.status==="READY_FOR_APPROVAL"&&<ArtisanReviewPanel request={request}/>}</SideCard> }
export function PricingCard({ request }: { request:ReviewRequest }) { return <SideCard title="ESTIMATED PRICE"><h3>{request.finalPrice?money(request.finalPrice,request.currency):`${money(request.estimatedPriceMin,request.currency)} – ${money(request.estimatedPriceMax,request.currency)}`}</h3><p>{request.finalPrice?"Final approved price for your creation.":"Final price will be confirmed after review. No payment is required at this stage."}</p><a href="#pricing">ⓘ &nbsp; Learn more about pricing</a></SideCard> }
export function CurrentActionCard({ request,onAction,onRevision }: {request:ReviewRequest;onAction:()=>void;onRevision:()=>void}) { return <SideCard title="CURRENT ACTION"><p>{WORKFLOW[request.status].description}</p><button className="od-primary" onClick={onAction}>{statusAction[request.status]}<span>→</span></button>{request.status==="READY_FOR_APPROVAL"&&<button className="od-secondary" onClick={onRevision}>Request Revision</button>}</SideCard> }
export function RequestSummaryCard({ request }: {request:ReviewRequest}) { return <SideCard title="ORDER SUMMARY"><dl><dt>Request No.</dt><dd>{request.requestNumber}</dd><dt>Country / Region</dt><dd>🇮🇩 {request.pricingRegion}</dd><dt>Submitted On</dt><dd>{formatDate(request.submittedAt)}</dd><dt>Concentration</dt><dd>{request.concentration}</dd><dt>Bottle Size</dt><dd>{request.bottleSize}</dd></dl></SideCard> }
export function ProductionTimeline({ request }: {request:ReviewRequest}) { if(!["IN_PRODUCTION","SHIPPED","COMPLETED"].includes(request.status))return null; return <SideCard title="PRODUCTION JOURNEY"><div className="od-mini-timeline"><span className="done">Formula development</span><span className={request.status!=="IN_PRODUCTION"?"done":""}>Sample & production</span><span className={["SHIPPED","COMPLETED"].includes(request.status)?"done":""}>Delivery</span></div></SideCard> }
export function ShipmentCard({ request }: {request:ReviewRequest}) { if(!["SHIPPED","COMPLETED"].includes(request.status))return null; return <SideCard title="SHIPMENT"><h3>{request.status==="COMPLETED"?"Delivered":"On its way"}</h3><p>Tracking no. HOA-ID-260718472</p></SideCard> }
export function CompletedActions() { return <SideCard title="YOUR CREATION"><button className="od-primary">View Hall Archive <span>→</span></button><button className="od-secondary">Create Another Perfume</button></SideCard> }

export function DevPanel({ request }: {request:ReviewRequest}) { if(!import.meta.env.DEV)return null;const actors:WorkflowActor[]=["customer","reviewer","admin","system"];return <aside className="od-dev"><strong>Developer simulation (validated transitions)</strong>{actors.flatMap(actor=>getAllowedTransitions(request.status,actor).map(status=><button key={`${actor}-${status}`} onClick={()=>void orderService.updateStatus(request.id,status,actor)}>{actor}: {status.replaceAll("_"," ")}</button>))}<button onClick={()=>void orderService.setFinalPrice(request.id,899000,"admin")}>Admin: Set Final Price</button>{request.status==="PAYMENT_PENDING"&&<button onClick={()=>void orderService.simulatePaymentConfirmation(request.id)}>System: Confirm Mock Payment</button>}<button onClick={()=>void orderService.sendMessage(request.id,"Development fixture message from an artisan.","artisan")}>Reviewer: Send Message</button></aside> }
