import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router";
import { useAuth } from "../../../contexts/AuthContext";
import AcademyProgressBar from "../components/AcademyProgressBar";
import LessonBlockRenderer from "../components/LessonBlockRenderer";
import { getCourseBySlug,getCourseCurriculum,getLessonBySlug,resolveCourseAccess,type CourseWithTranslations,type LessonReaderRecord,type ModuleWithCurriculum } from "../services/academyCatalogService";
import { getMyProgress,upsertMyLessonProgress,type AcademyProgress } from "../services/academyProgressService";
import { useAcademyLocale } from "../hooks/useAcademyLocale";
import { jsonStringArray,resolveAcademyTranslation } from "../utils/resolveAcademyTranslation";

export default function AcademyLessonPage(){const {courseSlug="",lessonSlug=""}=useParams();const {user}=useAuth();const {locale,t}=useAcademyLocale();const [course,setCourse]=useState<CourseWithTranslations|null>(null);const [modules,setModules]=useState<ModuleWithCurriculum[]>([]);const [lesson,setLesson]=useState<LessonReaderRecord|null>(null);const [progress,setProgress]=useState<AcademyProgress[]>([]);const [access,setAccess]=useState<Awaited<ReturnType<typeof resolveCourseAccess>>>("locked");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [drawer,setDrawer]=useState(false);const drawerButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{let active=true;void(async()=>{setLoading(true);setError("");try{const found=await getCourseBySlug(courseSlug);if(!found)return;const [curriculum,body,resolved,rows]=await Promise.all([getCourseCurriculum(found.id),getLessonBySlug(lessonSlug),resolveCourseAccess(courseSlug),user?getMyProgress(user.id):Promise.resolve([])]);if(!active)return;setCourse(found);setModules(curriculum);setLesson(body);setAccess(resolved);setProgress(rows);if(user&&body&&resolved==="actively_enrolled"){const existing=rows.find(row=>row.lesson_id===body.id);if(existing?.status!=="completed"){const updated=await upsertMyLessonProgress({lesson_id:body.id,status:"in_progress",last_block_position:existing?.last_block_position??0,started_at:existing?.started_at??new Date().toISOString(),last_opened_at:new Date().toISOString(),completed_at:null},user.id);if(active)setProgress(current=>[...current.filter(row=>row.lesson_id!==body.id),updated]);}else{const updated=await upsertMyLessonProgress({lesson_id:body.id,status:"completed",last_block_position:existing.last_block_position,last_opened_at:new Date().toISOString(),started_at:existing.started_at,completed_at:existing.completed_at},user.id);if(active)setProgress(current=>[...current.filter(row=>row.lesson_id!==body.id),updated]);}}}catch(reason){if(active)setError(reason instanceof Error?reason.message:t("lessonUnavailable"));}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[courseSlug,lessonSlug,user?.id]);
  const lessons=useMemo(()=>modules.flatMap(module=>module.academy_lessons),[modules]);const index=lessons.findIndex(item=>item.slug===lessonSlug);const previous=index>0?lessons[index-1]:null;const next=index>=0?lessons[index+1]??null:null;const progressMap=useMemo(()=>new Map(progress.map(row=>[row.lesson_id,row])),[progress]);const currentProgress=lesson?progressMap.get(lesson.id):null;const completed=lessons.filter(item=>progressMap.get(item.id)?.status==="completed").length;const courseTranslation=course?resolveAcademyTranslation(course.academy_course_translations,locale):null;const contentLocale=lesson?.academy_lesson_translations.some(item=>item.locale===locale)?locale:"en";const lessonTranslation=lesson?.academy_lesson_translations.find(item=>item.locale===contentLocale)??null;const canRead=Boolean(lesson&&(access==="actively_enrolled"||access==="admin"||lesson.is_preview));
  const closeDrawer=()=>{setDrawer(false);window.setTimeout(()=>drawerButton.current?.focus(),0);};const complete=async()=>{if(!user||!lesson||access!=="actively_enrolled"||saving)return;setSaving(true);setError("");try{const updated=await upsertMyLessonProgress({lesson_id:lesson.id,status:"completed",last_block_position:lesson.academy_lesson_blocks.length,started_at:currentProgress?.started_at??new Date().toISOString(),last_opened_at:new Date().toISOString(),completed_at:currentProgress?.completed_at??new Date().toISOString()},user.id);setProgress(rows=>[...rows.filter(row=>row.lesson_id!==lesson.id),updated]);}catch(reason){setError(reason instanceof Error?reason.message:t("lessonUnavailable"));}finally{setSaving(false);}};
  if(loading)return <main className="academy-page"><p className="academy-status" role="status">{t("openingLesson")}</p></main>;if(error&&!lesson)return <main className="academy-page"><section className="academy-empty-state"><h1>{t("lessonUnavailable")}</h1><p>{error}</p></section></main>;if(!course||!lesson||!lessonTranslation)return <main className="academy-page"><section className="academy-empty-state"><h1>{t("lessonUnavailable")}</h1><Link className="academy-button" to={`/academy/courses/${courseSlug}`}>{t("backToCourse")}</Link></section></main>;if(!canRead)return <main className="academy-page"><section className="academy-empty-state academy-locked"><p className="academy-eyebrow">{t("locked")}</p><h1>{lessonTranslation.title}</h1><p>{t("notEnrolled")}</p><Link className="academy-button academy-button--primary" to={`/academy/courses/${courseSlug}`}>{t("backToCourse")}</Link></section></main>;
  return <main className="academy-lesson-layout"><button ref={drawerButton} className="academy-contents-button" aria-expanded={drawer} onClick={()=>setDrawer(true)}>{t("openContents")}</button><aside className={`academy-reader-sidebar ${drawer?"is-open":""}`} aria-label={t("curriculum")}><button className="academy-drawer-close" onClick={closeDrawer}>{t("closeContents")}</button><Link to="/my-academy">← {t("backToMyAcademy")}</Link><h2>{courseTranslation?.title}</h2><AcademyProgressBar completed={completed} total={lessons.length} label={t("progress")}/><nav><ol>{lessons.map(item=>{const lt=item.academy_lesson_translations.find(value=>value.locale===contentLocale);return <li className={item.id===lesson.id?"active":""} key={item.id}><Link to={`/academy/courses/${courseSlug}/lessons/${item.slug}`} onClick={()=>setDrawer(false)}>{lt?.title??item.slug}</Link><small>{progressMap.get(item.id)?.status==="completed"?t("complete"):progressMap.get(item.id)?.status==="in_progress"?t("inProgress"):t("notStarted")}</small></li>;})}</ol></nav></aside>
    <article className="academy-reading-column"><header><p className="academy-eyebrow">{t("reader")} · {t("limitedBeta")}</p><h1>{lessonTranslation.title}</h1><p className="academy-opening-line">{lessonTranslation.opening_line}</p><div className="academy-reading-times"><span>{lesson.reading_minutes} {t("minutes")} {t("readingTime")}</span><span>{lesson.practice_minutes} {t("minutes")} {t("practiceTime")}</span></div><p>{lessonTranslation.introduction}</p></header><section className="academy-objectives"><h2>{t("objectives")}</h2><ul>{jsonStringArray(lessonTranslation.learning_objectives).map(item=><li key={item}>{item}</li>)}</ul></section>{lesson.academy_lesson_blocks.map(block=><LessonBlockRenderer key={block.id} block={block} translation={block.academy_lesson_block_translations.find(item=>item.locale===contentLocale)??null}/>)}{access==="actively_enrolled"?<div className="academy-completion"><button className="academy-button academy-button--primary" disabled={saving||currentProgress?.status==="completed"} onClick={()=>void complete()}>{saving?t("markingComplete"):currentProgress?.status==="completed"?t("lessonComplete"):t("markComplete")}</button>{currentProgress?.status==="completed"&&!next?<p>{t("noNextLesson")}</p>:null}</div>:null}<nav className="academy-lesson-nav" aria-label={t("contents")}>{previous?<Link to={`/academy/courses/${courseSlug}/lessons/${previous.slug}`}>← {t("previousLesson")}</Link>:<span/>}{next?<Link to={`/academy/courses/${courseSlug}/lessons/${next.slug}`}>{t("nextLesson")} →</Link>:<Link to={`/my-academy/courses/${courseSlug}`}>{t("courseOverview")} →</Link>}</nav></article>
    <aside className="academy-reader-utility"><h2>{t("materials")}</h2><ul>{jsonStringArray(lessonTranslation.materials_needed).map(item=><li key={item}>{item}</li>)}</ul><h2>{t("contents")}</h2><ol>{lesson.academy_lesson_blocks.map((block,index)=><li key={block.id}>{index+1}. {block.block_type.replaceAll("_"," ")}</li>)}</ol></aside>{drawer?<button className="academy-drawer-backdrop" aria-label={t("closeContents")} onClick={closeDrawer}/>:null}
  </main>;
}
