import { useEffect, useMemo, useState } from "react";
import { Link, Navigate, useLocation, useParams } from "react-router";
import { useAuth } from "../../../contexts/AuthContext";
import AcademyProgressBar from "../components/AcademyProgressBar";
import AcademyRouteFallback from "../components/AcademyRouteFallback";
import { getCourseBySlug,getCourseCurriculum,type CourseWithTranslations,type ModuleWithCurriculum } from "../services/academyCatalogService";
import { getMyEnrollment } from "../services/academyEnrollmentService";
import { getMyProgress,type AcademyProgress } from "../services/academyProgressService";
import { useAcademyLocale } from "../hooks/useAcademyLocale";
import { resolveAcademyTranslation } from "../utils/resolveAcademyTranslation";

export default function EnrolledCourseOverviewPage(){const {courseSlug=""}=useParams();const location=useLocation();const {user,loading:authLoading}=useAuth();const {locale,t}=useAcademyLocale();const [course,setCourse]=useState<CourseWithTranslations|null>(null);const [modules,setModules]=useState<ModuleWithCurriculum[]>([]);const [progress,setProgress]=useState<AcademyProgress[]>([]);const [enrolled,setEnrolled]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{if(!user)return;let active=true;void (async()=>{try{const found=await getCourseBySlug(courseSlug);if(!found)return;const [curriculum,enrollment,rows]=await Promise.all([getCourseCurriculum(found.id),getMyEnrollment(found.id,user.id),getMyProgress(user.id)]);if(active){setCourse(found);setModules(curriculum);setEnrolled(enrollment?.status==="active");setProgress(rows);}}catch(reason){if(active)setError(reason instanceof Error?reason.message:t("courseUnavailable"));}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[courseSlug,user?.id]);
  const lessons=useMemo(()=>modules.flatMap(module=>module.academy_lessons),[modules]);const progressMap=useMemo(()=>new Map(progress.map(row=>[row.lesson_id,row])),[progress]);const completed=lessons.filter(lesson=>progressMap.get(lesson.id)?.status==="completed").length;const current=[...lessons].sort((a,b)=>{const ad=progressMap.get(a.id)?.last_opened_at??"";const bd=progressMap.get(b.id)?.last_opened_at??"";return bd.localeCompare(ad);})[0]??lessons[0];const translation=course?resolveAcademyTranslation(course.academy_course_translations,locale):null;
  if(authLoading)return <AcademyRouteFallback/>;if(!user)return <Navigate to={`/artisan-login?returnTo=${encodeURIComponent(location.pathname)}`} replace/>;if(loading)return <main className="academy-page"><p className="academy-status">{t("loading")}</p></main>;if(error||!course||!translation)return <main className="academy-page"><section className="academy-empty-state"><h1>{t("courseUnavailable")}</h1><p>{error}</p></section></main>;if(!enrolled)return <Navigate to={`/academy/courses/${course.slug}`} replace/>;
  return <main className="academy-page" aria-labelledby="course-overview-title"><header className="academy-page-heading"><p className="academy-eyebrow">{t("courseOverview")}</p><h1 id="course-overview-title">{translation.title}</h1><AcademyProgressBar completed={completed} total={lessons.length} label={t("courseProgress")}/>{current?<Link className="academy-button academy-button--primary" to={`/academy/courses/${course.slug}/lessons/${current.slug}`}>{progressMap.has(current.id)?t("continueStudying"):t("openLesson")}</Link>:null}</header><section className="academy-curriculum academy-curriculum--student"><h2>{t("curriculum")}</h2>{modules.map(module=>{const mt=resolveAcademyTranslation(module.academy_module_translations,locale);return <article key={module.id}><h3>{mt?.title}</h3><ol>{module.academy_lessons.map(lesson=>{const lt=resolveAcademyTranslation(lesson.academy_lesson_translations,locale);const state=progressMap.get(lesson.id)?.status??"not_started";return <li key={lesson.id}><div><span>{lt?.title}</span><small>{state==="completed"?t("complete"):state==="in_progress"?t("inProgress"):t("notStarted")}</small></div><Link to={`/academy/courses/${course.slug}/lessons/${lesson.slug}`}>{state==="in_progress"?t("resumeLesson"):t("openLesson")}</Link></li>;})}</ol></article>;})}</section></main>;
}
