import { expect,test } from "@playwright/test";
import { customerSignIn } from "./helpers";

const email=process.env.E2E_ACADEMY_EMAIL??process.env.E2E_CUSTOMER_EMAIL;
const password=process.env.E2E_ACADEMY_PASSWORD??process.env.E2E_CUSTOMER_PASSWORD;
test.describe("live enrolled Academy journey",()=>{
  test.skip(!email||!password,"Provide E2E_ACADEMY_EMAIL and E2E_ACADEMY_PASSWORD for live enrollment/progress coverage.");
  test("student enrolls idempotently, reads, completes, and resumes",async({page})=>{await customerSignIn(page,email!,password!);await page.goto("/academy/courses/introduction-to-the-world-of-perfumery");const enroll=page.getByRole("button",{name:"Enroll for Free"});if(await enroll.isVisible()){await enroll.click();await expect(page).toHaveURL(/\/my-academy\/courses\/introduction-to-the-world-of-perfumery$/);}await page.goto("/academy/courses/introduction-to-the-world-of-perfumery");await expect(page.getByRole("link",{name:"Continue Studying"})).toBeVisible();await page.goto("/my-academy/courses/introduction-to-the-world-of-perfumery");await page.getByRole("link",{name:/Open Lesson|Resume Lesson/}).first().click();await expect(page.getByText("Before You Spray")).toBeVisible();const complete=page.getByRole("button",{name:"Mark Lesson Complete"});if(await complete.isEnabled())await complete.click();await expect(page.getByRole("button",{name:"Lesson complete"})).toBeDisabled();await page.goto("/my-academy");await expect(page.getByText("Introduction to the World of Perfumery")).toBeVisible();await expect(page.getByRole("link",{name:"Resume Lesson"})).toBeVisible();});
  test("Pixel 7 reader drawer works and returns focus",async({page})=>{await page.setViewportSize({width:412,height:915});await customerSignIn(page,email!,password!);await page.goto("/academy/courses/introduction-to-the-world-of-perfumery/lessons/how-to-smell-a-perfume");const trigger=page.getByRole("button",{name:"Open lesson contents"});await trigger.click();await expect(page.getByRole("navigation").filter({hasText:"How to Smell a Perfume"})).toBeVisible();await page.getByRole("button",{name:"Close lesson contents"}).first().click();await expect(trigger).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);});
});
